const express = require('express')
const bodyParser = require('body-parser')

const app = express()
const port = 3000

app.use(bodyParser.json())

//--- generated by ChatGPT
let tasks = [
    {
        id: 1,
        title: "Complete the project",
        description: "Finish all remaining tasks for the project by the end of the month.",
        done: false,
        dueDate: "2024-06-30",
        createdAt: new Date().toISOString()
    },
    {
        id: 2,
        title: "Prepare meeting notes",
        description: "Gather all necessary documents and prepare notes for the upcoming client meeting.",
        done: false,
        dueDate: "2024-06-15",
        createdAt: new Date().toISOString()
    },
    {
        id: 3,
        title: "Update software",
        description: "Update all office computers with the latest security patches and software updates.",
        done: true,
        dueDate: "2024-06-10",
        createdAt: new Date().toISOString()
    }
];
//---

app.get('/tasks', (req, res) => {
    res.json(tasks)
});

app.post('/tasks', (req, res) => {
    if (isTaskStructureCorrect(req, res)) {
        const { title, description, done, dueDate } = req.body

        const nextId = tasks.reduce((maxId, task) => Math.max(maxId, task.id), 0) + 1

        const newTask = { id: nextId, title, description, done, dueDate, createdAt: new Date() }
        tasks.push(newTask);
        res.status(201).send(`task ${title} created`)
    }
});

function isTaskStructureCorrect(req, res) {
    const { title, description, done, dueDate } = req.body
    if (!title || !description || done === undefined || !dueDate) {
        res.status(422).send('task structure not right')
        return false
    }
    return true
}

app.listen(port, () => console.log(`Listening on port ${port}`))